version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file lambda1/lambda1_template.yaml --s3-bucket tests3bucket-test --output-template-file lambda1-output-template.yaml
artifacts:  
  type: zip
  files:
    - lambda1-output-template.yaml