version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket tests3bucket-test --output-template-file output-template.yaml
artifacts:  
  type: zip
  files:
    - output-template.yaml