AWSTemplateFormatVersion: '2010-09-09'  
Transform: 'AWS::Serverless-2016-10-31'  
Description: Lambda - Quotes  
Resources:  
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda-cicd-test
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Description: Lambda - Quotes
      MemorySize: 128
      Timeout: 7
      Role: arn:aws:iam::820656827628:role/LambdaRoleExample
        